<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.4" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
    <PackageReference Include="Tempest.Blazor" Version="1.0.0-beta.6" />
    <PackageReference Include="Tempest.Abstract" Version="1.0.0-beta.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoData.Common.Pagination\EcoData.Common.Pagination.csproj" />
    <ProjectReference Include="..\EcoData.Spa.Contracts\EcoData.Spa.Contracts.csproj" />
    <ProjectReference Include="..\EcoData.Spa.Core\EcoData.Spa.Core.csproj" />
  </ItemGroup>

</Project>
