; PlatformIO configuration for EcoData Water Sensor
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
build_unflags = -std=gnu++17
build_flags =
    -std=gnu++23
    -DCORE_DEBUG_LEVEL=3

[env:esp32]
board = esp32dev

[env:esp32s3]
board = esp32-s3-devkitc-1

[env:esp32c3]
board = esp32-c3-devkitm-1
