// <auto-generated />
using System;
using EcoData.Sensors.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoData.Sensors.Database.Migrations
{
    [DbContext(typeof(SensorsDbContext))]
    [Migration("20260422004954_AddUserSubscriptionsAndNotifications")]
    partial class AddUserSubscriptionsAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<double?>("ThresholdMax")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_max");

                    b.Property<double?>("ThresholdMin")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_min");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_alerts_triggered_at");

                    b.HasIndex("SensorId", "Resolved")
                        .HasDatabaseName("ix_alerts_sensor_id_resolved");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<DateTimeOffset>("LastRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recorded_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_logs");

                    b.HasIndex("DataSourceId", "IngestedAt")
                        .HasDatabaseName("ix_ingestion_logs_data_source_id_ingested_at");

                    b.ToTable("ingestion_logs", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.HasKey("Id")
                        .HasName("pk_parameters");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_parameters_code");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_parameters_sensor_type_id");

                    b.ToTable("parameters", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_readings");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_readings_recorded_at");

                    b.HasIndex("SensorId", "RecordedAt")
                        .HasDatabaseName("ix_readings_sensor_id_recorded_at");

                    b.HasIndex("SensorId", "Parameter", "RecordedAt")
                        .HasDatabaseName("ix_readings_sensor_id_parameter_recorded_at");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ReportingMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reporting_mode");

                    b.Property<Guid?>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_sensors_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_sensors_municipality_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sensors_organization_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_sensors_sensor_type_id");

                    b.HasIndex("OrganizationId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_organization_id_external_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorHealthAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alert_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_health_alerts");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_sensor_health_alerts_sensor_id");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_sensor_health_alerts_triggered_at");

                    b.HasIndex("SensorId", "ResolvedAt")
                        .HasDatabaseName("ix_sensor_health_alerts_sensor_id_resolved_at");

                    b.ToTable("sensor_health_alerts", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorHealthConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("expected_interval_seconds");

                    b.Property<bool>("IsMonitoringEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monitoring_enabled");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<int>("StaleThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("stale_threshold_seconds");

                    b.Property<int>("UnhealthyThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("unhealthy_threshold_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_health_configs");

                    b.HasIndex("SensorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_health_configs_sensor_id");

                    b.ToTable("sensor_health_configs", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorHealthStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset?>("LastReadingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reading_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_health_statuses");

                    b.HasIndex("SensorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_health_statuses_sensor_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sensor_health_statuses_status");

                    b.ToTable("sensor_health_statuses", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sensor_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_types_code");

                    b.ToTable("sensor_types", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_notifications");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("ix_user_notifications_alert_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_notifications_created_at");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_user_notifications_sensor_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_notifications_user_id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_user_notifications_user_id_is_read");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.UserSensorSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("NotifyOnRecovered")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_recovered");

                    b.Property<bool>("NotifyOnStale")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_stale");

                    b.Property<bool>("NotifyOnUnhealthy")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_unhealthy");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sensor_subscriptions");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_user_sensor_subscriptions_sensor_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sensor_subscriptions_user_id");

                    b.HasIndex("UserId", "SensorId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sensor_subscriptions_user_id_sensor_id");

                    b.ToTable("user_sensor_subscriptions", (string)null);
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Alert", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Parameter", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.SensorType", "SensorType")
                        .WithMany("Parameters")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parameters_sensor_types_sensor_type_id");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Reading", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Sensor", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sensors_sensor_types_sensor_type_id");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorHealthAlert", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithMany("HealthAlerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_health_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorHealthConfig", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithOne("HealthConfig")
                        .HasForeignKey("EcoData.Sensors.Database.Models.SensorHealthConfig", "SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_health_configs_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorHealthStatus", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithOne("HealthStatus")
                        .HasForeignKey("EcoData.Sensors.Database.Models.SensorHealthStatus", "SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_health_statuses_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.UserNotification", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.SensorHealthAlert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_notifications_sensor_health_alerts_alert_id");

                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_sensors_sensor_id");

                    b.Navigation("Alert");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.UserSensorSubscription", b =>
                {
                    b.HasOne("EcoData.Sensors.Database.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sensor_subscriptions_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("HealthAlerts");

                    b.Navigation("HealthConfig");

                    b.Navigation("HealthStatus");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("EcoData.Sensors.Database.Models.SensorType", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
