using EcoData.Common.i18n;

namespace FaunaFinder.Client.Localization;

public static class FaunaFinderStrings
{
    public static IReadOnlyList<ILanguage> Languages { get; } =
    [
        new Language("en", "English", IsDefault: true),
        new Language("es", "Español"),
    ];

    public static IReadOnlyList<ITranslation> Translations
    {
        get
        {
            var list = new List<ITranslation>(En.Count * 2);
            foreach (var (key, value) in En)
            {
                list.Add(new Translation("en", key, value));
            }
            foreach (var (key, value) in Es)
            {
                list.Add(new Translation("es", key, value));
            }
            return list;
        }
    }

    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        ["Common_Loading"] = "Loading…",
        ["Common_Cancel"] = "Cancel",
        ["Common_Apply"] = "Apply",
        ["Common_Close"] = "Close",
        ["Common_Back"] = "Back",
        ["Common_ViewDetails"] = "View details",
        ["Common_ViewAll"] = "View all",
        ["Common_Search"] = "Search",
        ["Common_Sort"] = "Sort",
        ["Common_Clear"] = "Clear",
        ["Common_SelectAll"] = "Select all",
        ["Common_ClearAll"] = "Clear all",
        ["Common_SearchOff"] = "No results",
        ["Common_Verified"] = "Verified",

        ["Nav_Map"] = "Map",
        ["Nav_Browse"] = "Browse",
        ["Nav_Species"] = "Species",
        ["Nav_Municipios"] = "Municipios",
        ["Nav_Categories"] = "Categories",
        ["Nav_Practices"] = "Practices",
        ["Nav_Actions"] = "Actions",

        ["Rail_Heading"] = "Field notebook",
        ["Rail_Tab_Municipios"] = "Municipios",
        ["Rail_Tab_Taxa"] = "Taxa",
        ["Rail_Empty"] = "Nothing recorded yet.",
        ["Rail_Collapse"] = "Collapse the notebook",
        ["Rail_Expand"] = "Open the notebook",
        ["Shell_Search"] = "Search species and municipios",
        ["Shell_Search_Searching"] = "Searching…",
        ["Shell_Search_Empty"] = "Nothing found for “{0}”.",
        ["Shell_Search_Clear"] = "Clear search",

        ["Browse_PageTitle"] = "Browse",
        ["Browse_Eyebrow"] = "Reference · Puerto Rico",
        ["Browse_Heading"] = "The catalogue behind the map.",
        ["Browse_Lede"] = "Three ways into the same record: by what a species is, by the conservation work that protects it, and by the recovery actions that work delivers.",
        ["Browse_Categories_Desc"] = "Every taxonomic group recorded on the island, with the species catalogued under each.",
        ["Browse_Practices_Desc"] = "NRCS conservation practices, each paired with the recovery actions it carries.",
        ["Browse_Actions_Desc"] = "Fish & Wildlife Service recovery actions, and the practices that deliver them.",
        ["Browse_Count_Pending"] = "—",
        ["Theme_ToDark"] = "Switch to dark",
        ["Theme_ToLight"] = "Switch to paper",

        ["Rail_Tab_Saved"] = "Saved",
        ["Rail_Tab_Nearby"] = "Near me",
        ["Rail_Saved_Empty"] = "Star a species or municipio to keep it here.",
        ["Rail_Nearby_Empty"] = "Nothing recorded within {0} km.",
        ["Rail_Nearby_Prompt"] = "Use my location",
        ["Rail_Nearby_Locating"] = "Finding you…",
        ["Rail_Nearby_Denied"] = "Location permission was declined.",
        ["Rail_Nearby_Unsupported"] = "This browser can't share a location.",
        ["Rail_Nearby_Origin"] = "Within {0} km of you",
        ["Rail_Distance_M"] = "{0} m",
        ["Rail_Distance_Km"] = "{0} km",
        ["Notebook_Save"] = "Save to notebook",
        ["SpeciesDetail_Report"] = "Download PDF report",
        ["Notebook_Unsave"] = "Remove from notebook",
        ["Notebook_Saved"] = "Saved",
        ["Time_JustNow"] = "just now",
        ["Time_MinutesAgo"] = "{0} min ago",
        ["Time_HoursAgo"] = "{0} h ago",
        ["Time_DaysAgo"] = "{0} d ago",

        ["Hero_Eyebrow"] = "Volume 03 · Living Atlas",
        ["Hero_LastSync"] = "Last sync · {0}",

        ["Species_PageTitle"] = "FaunaFinder — Species",
        ["Species_Hero_HeadingLead"] = "Species of",
        ["Species_Hero_HeadingTail"] = ", catalogued and observed.",
        ["Species_Hero_Lede"] = "A living field guide to the island's flora and fauna — drawn from verified sightings across 78 municipios. Browse by taxon, conservation status, or habitat; follow any record through to its distribution map and source observations.",
        ["Species_Hero_RecordsLine"] = "{0} records · {1} municipios",
        ["Species_Hero_UpdatedDaily"] = "Updated daily",
        ["Species_Hero_RecordsPending"] = "— records · — municipios",

        ["Species_Stats_Total_Label"] = "Total species",
        ["Species_Stats_Total_Sub_Delta"] = "{0} this quarter",
        ["Species_Stats_Total_Sub_None"] = "—",
        ["Species_Stats_Endemic_Label"] = "Endemic to P.R.",
        ["Species_Stats_Endemic_Sub"] = "{0}% of catalogue",
        ["Species_Stats_Threatened_Label"] = "Threatened · VU–CR",
        ["Species_Stats_Threatened_Sub_Delta"] = "{0} reclassified",
        ["Species_Stats_Municipios_Label"] = "Municipios covered",
        ["Species_Stats_Municipios_Sub"] = "{0}% of {1} municipios + {2} Virgin Islands",

        ["Species_Featured_Heading"] = "Featured this week",
        ["Species_Featured_Meta"] = "Curated · updated Mondays",

        ["Species_Toolbar_Heading"] = "Find what you're looking for",
        ["Species_Toolbar_RecordsMeta"] = "{0} records · {1} municipios",
        ["Species_Toolbar_RecordsMeta_Loading"] = "Loading catalogue…",
        ["Species_Toolbar_SearchPlaceholder"] = "Search by common name, scientific name, or species…",
        ["Species_Toolbar_Counter_Of"] = "of {0}",
        ["Species_Toolbar_Sort_Prefix"] = "Sort:",
        ["Species_Toolbar_Sort_ScientificAsc"] = "Scientific name ↑",
        ["Species_Toolbar_Sort_ScientificDesc"] = "Scientific name ↓",
        ["Species_Toolbar_Sort_Recent"] = "Recently observed",
        ["Species_Toolbar_Sort_MostWidespread"] = "Most widespread",

        ["Species_Chip_Taxon"] = "Taxon: {0}",
        ["Species_Chip_Status"] = "Status: {0}",
        ["Species_Chip_Endemic"] = "Endemic only",
        ["Species_Chip_ObservedRecently"] = "Observed in last 12 months",
        ["Species_Chip_HasPhoto"] = "Has photo",
        ["Species_Chip_MinMunicipios"] = "≥ {0} municipios",

        ["Species_Filter_Heading"] = "Refine the catalogue",
        ["Species_Filter_TotalRecords"] = "{0} records",
        ["Species_Filter_Section_Taxa"] = "Taxonomic group",
        ["Species_Filter_Section_Status"] = "Conservation status (IUCN)",
        ["Species_Filter_Section_Qualifiers"] = "Qualifiers",
        ["Species_Filter_Section_MinMunicipios"] = "Minimum municipios present",
        ["Species_Filter_Qualifier_EndemicLabel"] = "Endemic to Puerto Rico only",
        ["Species_Filter_Qualifier_ObservedLabel"] = "Observed in the last 12 months",
        ["Species_Filter_Qualifier_HasPhotoLabel"] = "Has photo",
        ["Species_Filter_StatusMeta_Selected"] = "{0} selected",
        ["Species_Filter_MinMunicipios_Meta"] = "≥ {0}",
        ["Species_Filter_MinMunicipios_Rare"] = "1 (rare)",
        ["Species_Filter_MinMunicipios_Ubiquitous"] = "78 (ubiquitous)",
        ["Species_Filter_Reset"] = "Reset all filters",

        ["Species_Taxa_Bird"] = "Bird",
        ["Species_Taxa_Plant"] = "Plant",
        ["Species_Taxa_Reptile"] = "Reptile",
        ["Species_Taxa_Amphib"] = "Amphibian",
        ["Species_Taxa_Fish"] = "Fish",
        ["Species_Taxa_Mammal"] = "Mammal",
        ["Species_Taxa_Invert"] = "Invertebrate",
        ["Species_Taxa_Fungi"] = "Fungus",

        ["Species_Iucn_LC"] = "Least Concern",
        ["Species_Iucn_NT"] = "Near Threatened",
        ["Species_Iucn_VU"] = "Vulnerable",
        ["Species_Iucn_EN"] = "Endangered",
        ["Species_Iucn_CR"] = "Critically Endangered",
        ["Species_Iucn_DD"] = "Data Deficient",
        ["Species_Iucn_EX"] = "Extinct",

        ["Species_Card_Municipios"] = "{0} municipios",
        ["Species_Card_EndemicBadge"] = "Endemic PR",
        ["Species_Grid_LoadingMore"] = "Loading more records…",
        ["Species_Grid_LoadMore"] = "Load more records",
        ["Species_Grid_EndOfCatalogue"] = "— end of catalogue —",
        ["Species_Grid_Empty_Title"] = "No species match",
        ["Species_Grid_Empty_Description"] = "Try adjusting your filters or search terms.",

        ["Time_MinutesAgo"] = "{0}m ago",
        ["Time_HoursAgo"] = "{0}h ago",
        ["Time_DaysAgo"] = "{0}d ago",
        ["Time_MonthsAgo"] = "{0}mo ago",
        ["Time_YearsAgo"] = "{0}y ago",

        ["SpeciesDetail_Rank_Global"] = "Global: {0}",
        ["SpeciesDetail_Rank_State"] = "State: {0}",
        ["SpeciesDetail_Kingdom_Fauna"] = "Fauna",
        ["SpeciesDetail_Kingdom_Flora"] = "Flora",
        ["SpeciesDetail_ElCode"] = "Element Code: {0}",
        ["SpeciesDetail_Categories_Heading"] = "Categories",
        ["SpeciesDetail_Municipalities_Heading"] = "Municipalities",
        ["SpeciesDetail_Municipalities_Empty_Title"] = "No municipalities",
        ["SpeciesDetail_Municipalities_Empty_Description"] = "This species has no recorded municipality associations yet.",
        ["SpeciesDetail_NotFound_Title"] = "Species not found",
        ["SpeciesDetail_NotFound_Description"] = "The species you're looking for doesn't exist or has been removed.",

        ["Muni_PageTitle"] = "FaunaFinder — Municipios",
        ["Muni_Hero_HeadingLead"] = "Municipios of",
        ["Muni_Hero_HeadingTail"] = ", mapped and observed.",
        ["Muni_Hero_Lede"] = "A geographic index to Puerto Rico's 78 municipios — each annotated with the species recorded inside its boundaries. Search by name, sort by biodiversity, or tap any pin to pull up a municipio's full roster and its notable residents.",
        ["Muni_Hero_RecordsLine"] = "{0} municipios · {1} records",
        ["Muni_Hero_RecordsPending"] = "— municipios · — records",
        ["Muni_Hero_Hint"] = "Tap a pin or row to drill in",

        ["Muni_Stats_Total_Label"] = "Total municipios",
        ["Muni_Stats_Total_Unit"] = "/ {0} tracked",
        ["Muni_Stats_Total_Sub"] = "{0} municipios + {1} U.S. Virgin Islands",
        ["Muni_Stats_Species_Label"] = "Species catalogued",
        ["Muni_Stats_Species_Sub"] = "across the island",
        ["Muni_Stats_Avg_Label"] = "Avg · species / municipio",
        ["Muni_Stats_Avg_Sub"] = "{0} municipios contribute",
        ["Muni_Stats_Hotspots_Label"] = "Endemic hotspots",
        ["Muni_Stats_Hotspots_Sub"] = "≥ 10 endemic species present",

        ["Muni_Tab_Map"] = "Map",
        ["Muni_Tab_List"] = "List",

        ["Muni_List_SearchPlaceholder"] = "Search municipios by name…",
        ["Muni_List_VisibleAll"] = "{0} municipios",
        ["Muni_List_VisibleFiltered"] = "{0} of {1}",
        ["Muni_List_Loading"] = "Loading…",
        ["Muni_List_Sort_SpeciesCountDesc"] = "species count ↓",
        ["Muni_List_Sort_NameAsc"] = "name A–Z",
        ["Muni_List_Sort_Prefix"] = "Sort:",
        ["Muni_List_Empty"] = "No municipios match \"{0}\"",
        ["Muni_List_Foot_Loading"] = "loading municipios",
        ["Muni_List_Foot_Total"] = "{0} municipios tracked",

        ["Muni_Map_Legend_Title"] = "Municipios",
        ["Muni_Map_Legend_Selected"] = "Selected",
        ["Muni_Map_Legend_Boundary"] = "Boundary",
        ["Muni_DetailCard_Species_Label"] = "Species",
        ["Muni_DetailCard_Fips_Label"] = "FIPS",
        ["Muni_DetailCard_CountRecorded"] = "{0} species recorded",
        ["Muni_DetailCard_CountPending"] = "Species count pending",
        ["Muni_Card_SpeciesCount"] = "{0} species",

        ["MuniDetail_Subline"] = "{0} · FIPS {1}",
        ["MuniDetail_Centroid"] = "Centroid · {0}″N {1}″W",
        ["MuniDetail_Species_Heading"] = "Species",
        ["MuniDetail_Species_Empty_Title"] = "No species recorded",
        ["MuniDetail_Species_Empty_Description"] = "No species have been associated with this municipio yet.",
        ["MuniDetail_NotFound_Title"] = "Municipio not found",
        ["MuniDetail_NotFound_Description"] = "The municipio you're looking for doesn't exist or has been removed.",

        ["Categories_PageTitle"] = "Categories",
        ["Categories_Empty_Title"] = "No categories",
        ["Categories_Empty_Description"] = "No species categories have been created yet.",
        ["CategoryDetail_SpeciesCount"] = "{0} Species",
        ["CategoryDetail_Empty_Title"] = "No species",
        ["CategoryDetail_Empty_Description"] = "No species have been categorized here yet.",

        ["Practices_PageTitle"] = "Practices",
        ["Practices_Hero_HeadingLead"] = "Conservation work in",
        ["Practices_Hero_HeadingTail"] = ", practice by practice.",
        ["Practices_Hero_Lede"] = "The NRCS conservation practices behind the island's recovery work — each one paired with the Fish & Wildlife Service actions it carries and the species those actions protect. Open a practice to read its actions, then follow any one through to the species it applies to.",
        ["Practices_Hero_RecordsLine"] = "{0} practices catalogued",
        ["Practices_Hero_RecordsPending"] = "— practices catalogued",
        ["Practices_Hero_Hint"] = "Tap a practice to see its actions",
        ["Practices_Empty_Title"] = "No practices",
        ["Practices_Empty_Description"] = "No NRCS conservation practices have been loaded yet.",
        ["PracticeDetail_Subline"] = "NRCS conservation practice",
        ["PracticeDetail_Actions_Heading"] = "FWS Actions",
        ["PracticeDetail_Actions_Empty_Title"] = "No actions",
        ["PracticeDetail_Actions_Empty_Description"] = "No FWS actions are linked to this practice yet.",
        ["PracticeDetail_ActionCode"] = "FWS {0}",
        ["PracticeDetail_ActionSpeciesCount"] = "{0} species",
        ["PracticeDetail_Species_Heading"] = "Species",
        ["PracticeDetail_SpeciesCount"] = "{0} Species",
        ["PracticeDetail_Empty_Title"] = "No species",
        ["PracticeDetail_Empty_Description"] = "No species are linked to this conservation practice yet.",

        ["Actions_PageTitle"] = "Actions",
        ["Actions_Hero_HeadingLead"] = "What recovery asks of",
        ["Actions_Hero_HeadingTail"] = ", action by action.",
        ["Actions_Hero_Lede"] = "The Fish & Wildlife Service actions that shape recovery on the island — each one carried out through the NRCS conservation practices that fund and field it. Open an action to see which practices deliver it, and the species it was written for.",
        ["Actions_Hero_RecordsLine"] = "{0} actions catalogued",
        ["Actions_Hero_RecordsPending"] = "— actions catalogued",
        ["Actions_Hero_Hint"] = "Tap an action to see its practices",
        ["Actions_Empty_Title"] = "No actions",
        ["Actions_Empty_Description"] = "No FWS conservation actions have been loaded yet.",
        ["ActionDetail_Subline"] = "FWS conservation action",
        ["ActionDetail_Practices_Heading"] = "Conservation Practices",
        ["ActionDetail_Practices_Empty_Title"] = "No practices",
        ["ActionDetail_Practices_Empty_Description"] = "No NRCS conservation practices are linked to this action yet.",
        ["ActionDetail_PracticeCode"] = "NRCS {0}",
        ["ActionDetail_PracticeSpeciesCount"] = "{0} species",
        ["ActionDetail_Species_Heading"] = "Species",
        ["ActionDetail_SpeciesCount"] = "{0} Species",
        ["ActionDetail_Empty_Title"] = "No species",
        ["ActionDetail_Empty_Description"] = "No species are linked to this conservation action yet.",

        ["Home_SidebarEmpty"] = "Tap a municipio to see its species",
        ["Map_Panel_Eyebrow"] = "Municipio",
        ["Map_Panel_NoSpecies_Title"] = "No species recorded",
        ["Map_Panel_NoSpecies_Description"] = "No species have been observed in this municipio yet.",
        ["Map_Panel_SpeciesObserved"] = "{0} species observed",
        ["Map_NearMe_Label"] = "Species near me",
        ["Map_NearMe_Title"] = "Near me",
        ["Map_NearMe_Eyebrow"] = "Within {0} km",
        ["Map_DrawArea_Label"] = "Draw area",
        ["Map_DrawArea_Title"] = "Drawn area",
        ["Map_DrawArea_Eyebrow"] = "Custom search",
        ["Map_Draw_Instructions"] = "Click the map to add points. Double-click, press Enter, or click the first point to finish. Esc cancels.",
        ["Map_Draw_Finish"] = "Finish",
        ["Map_Draw_Cancel"] = "Cancel",
        ["Map_Heatmap_Show"] = "Heatmap",
        ["Map_Heatmap_Hide"] = "Hide heatmap",
        ["Map_Heatmap_All"] = "All",
        ["Map_Heatmap_Fauna"] = "Fauna",
        ["Map_Heatmap_Flora"] = "Flora",
        ["Map_Travel_Label"] = "Travel to another region",
        ["Map_Travel_Title"] = "Travel to…",
        ["Map_Region_PuertoRico"] = "Puerto Rico",
        ["Map_Region_PuertoRico_Subtitle"] = "78 municipios",
        ["Map_Region_VirginIslands"] = "U.S. Virgin Islands",
        ["Map_Region_VirginIslands_Subtitle"] = "3 islands",
        ["Map_Nearby_Empty_Title"] = "No species found",
        ["Map_Nearby_Empty_Description"] = "No recorded species locations in this area.",
        ["Map_Nearby_Count"] = "{0} species found",
        ["Map_Location_Unnamed"] = "Unnamed location",
        ["Map_Location_RadiusMeters"] = "{0} m radius",
        ["Map_ViewDetails"] = "Details",
        ["Map_ViewLocations"] = "View on map",
        ["Map_Geolocation_Denied"] = "Location permission was denied. Enable it in your browser to search near you.",
        ["Map_Geolocation_Unavailable"] = "Your location could not be determined. Please try again.",
        ["Map_Geolocation_Unsupported"] = "Your browser does not support geolocation.",
        ["Map_NoLocations_ForSpecies"] = "This species has no recorded locations yet.",
        ["Map_Filter_Title"] = "Filters",
        ["Map_Filter_Label"] = "Filter by conservation practice",
        ["Map_Filter_NrcsPractices"] = "NRCS practices",
        ["Map_Filter_FwsActions"] = "FWS actions",
        ["Map_Filter_ClearAll"] = "Clear all",
        ["Map_Filter_Apply"] = "Apply",
        ["Map_Filter_Showing"] = "Showing {0} of {1} species",

        ["Auth_SignIn"] = "Sign in",
        ["Auth_SignOut"] = "Sign out",
        ["Auth_SigningIn"] = "Signing in…",
        ["Auth_CreateAccount"] = "Create account",
        ["Auth_CreatingAccount"] = "Creating your account…",
        ["Auth_AccountLabel"] = "Account",
        ["Auth_WelcomeBack"] = "Welcome back",
        ["Auth_JoinTitle"] = "Join FaunaFinder",
        ["Auth_Email"] = "Email",
        ["Auth_Password"] = "Password",
        ["Auth_ConfirmPassword"] = "Confirm password",
        ["Auth_DisplayName"] = "Display name",
        ["Auth_StudentQuestion"] = "Are you a student of the Inter Metro University?",
        ["Auth_Yes"] = "Yes",
        ["Auth_No"] = "No",
        ["Auth_NoAccount"] = "Don't have an account?",
        ["Auth_HaveAccount"] = "Already have an account?",
        ["Auth_Request_Pending"] = "Student access: pending approval",
        ["Auth_Request_Approved"] = "Student access: approved",
        ["Auth_Request_Rejected"] = "Student access: not approved",
        ["Auth_RequestNotSubmitted"] = "Your account was created, but the student access request could not be sent. Please try again later.",
        ["Auth_ServerUnreachable"] = "Couldn't reach the server. Please try again.",
        ["Auth_SignInFailed"] = "Something went wrong while signing in. Please try again.",
        ["Auth_SignUpFailed"] = "Something went wrong while creating your account. Please try again.",

        ["Sighting_Report_PageTitle"] = "Report a sighting",
        ["Sighting_Report_Title"] = "Report a sighting",
        ["Sighting_Report_Action"] = "Report a sighting",
        ["Sighting_Report_Lede"] = "Tell us what you saw and where. A FaunaFinder reviewer checks every report before it joins the catalogue.",
        ["Sighting_Species"] = "Species",
        ["Sighting_Species_Placeholder"] = "Search by common or scientific name",
        ["Sighting_Species_NoResults"] = "No species match that search.",
        ["Sighting_Species_Required"] = "Pick the species you saw.",
        ["Sighting_Location"] = "Location",
        ["Sighting_Location_Hint"] = "Tap the map to place the marker, or use your location.",
        ["Sighting_Location_Required"] = "Place the marker where you saw it.",
        ["Sighting_UseMyLocation"] = "Use my location",
        ["Sighting_Municipality_Resolving"] = "Finding the municipio…",
        ["Sighting_Municipality_Outside"] = "Outside any municipio",
        ["Sighting_Municipality_Unknown"] = "Municipio could not be determined",
        ["Sighting_ObservedAt"] = "Observed",
        ["Sighting_ObservedDate"] = "Date observed",
        ["Sighting_ObservedTime"] = "Time observed",
        ["Sighting_ObservedAt_Required"] = "Enter when you saw it.",
        ["Sighting_Count"] = "How many",
        ["Sighting_Count_Hint"] = "Optional. Number of individuals you saw.",
        ["Sighting_Count_Value"] = "Count: {0}",
        ["Sighting_Note"] = "Note",
        ["Sighting_Note_Hint"] = "Optional. Behaviour, habitat, anything that helps a reviewer.",
        ["Sighting_Submit"] = "Send report",
        ["Sighting_Submitting"] = "Sending…",
        ["Sighting_Unavailable"] = "Reporting is temporarily unavailable. Please try again in a moment.",
        ["Sighting_Report_Success"] = "Thanks! Your sighting was sent for review.",
        ["Sighting_Error_Unreachable"] = "Couldn't reach the server. Please try again.",
        ["Sighting_Error_SignedOut"] = "Your session has ended. Please sign in again.",
        ["Sighting_Error_Forbidden"] = "You don't have permission to do that.",
        ["Sighting_Error_NotFound"] = "That sighting or species no longer exists.",
        ["Sighting_Error_TooMany"] = "Too many requests. Please wait a moment and try again.",
        ["Sighting_Error_Generic"] = "Something went wrong. Please try again.",
        ["Sighting_Mine_PageTitle"] = "My sightings",
        ["Sighting_Mine_Title"] = "My sightings",
        ["Sighting_Mine_Lede"] = "Everything you have reported, newest first, with where each report stands.",
        ["Sighting_Mine_Empty_Title"] = "No sightings yet",
        ["Sighting_Mine_Empty_Description"] = "Spot something? Report it and it will show up here.",
        ["Sighting_Status_Pending"] = "Pending",
        ["Sighting_Status_Approved"] = "Approved",
        ["Sighting_Status_Denied"] = "Denied",
        ["Sighting_Coordinates"] = "Coordinates",
        ["Sighting_ReportedAt"] = "Reported",
        ["Sighting_Photos"] = "Photos",
        ["Sighting_Review"] = "Review",
        ["Sighting_ReviewedBy"] = "Reviewed by {0} on {1}",
        ["Sighting_Notes"] = "Notes",
        ["Sighting_Notes_Empty"] = "No notes yet. Reviewers may ask questions here.",
        ["Sighting_Note_Add"] = "Add a note",
        ["Sighting_Note_Send"] = "Send",
        ["Sighting_Image_Add"] = "Add photos",
        ["Sighting_Image_Hint"] = "Up to 5 photos, 10 MB each (JPEG, PNG or WebP).",
        ["Sighting_Image_Empty"] = "No photos yet.",
        ["Sighting_Image_TooMany"] = "You can attach up to {0} photos.",
        ["Sighting_Image_TooLarge"] = "{0} is larger than 10 MB.",
        ["Sighting_Image_NotImage"] = "{0} is not an image.",
        ["Sighting_Image_UploadFailed"] = "{0} could not be uploaded.",
        ["Sighting_Image_Uploading"] = "Uploading photos…",
        ["Sighting_Image_View"] = "View photo",
        ["Sighting_Image_Close"] = "Close photo",
        ["Sighting_Image_Delete"] = "Delete photo",
        ["Sighting_Image_Delete_Confirm"] = "Delete this photo? This cannot be undone.",
        ["Sighting_Image_DeleteFailed"] = "The photo could not be deleted.",
        ["Sighting_Review_Nav"] = "Review sightings",
        ["Sighting_Review_PageTitle"] = "Review sightings",
        ["Sighting_Review_Title"] = "Review sightings",
        ["Sighting_Review_Lede"] = "Sightings reported to {0}. Approving one publishes it to the catalogue.",
        ["Sighting_Review_Filter_Species"] = "Filter by species",
        ["Sighting_Review_Empty_Title"] = "Nothing here",
        ["Sighting_Review_Empty_Pending"] = "No pending sightings. New reports will show up here.",
        ["Sighting_Review_Empty_Approved"] = "No approved sightings match this filter.",
        ["Sighting_Review_Empty_Denied"] = "No denied sightings match this filter.",
        ["Sighting_Review_LoadMore"] = "Load more",
        ["Sighting_Review_ReportedBy"] = "Reported by {0}",
        ["Sighting_Review_Reporter"] = "Reporter",
        ["Sighting_Review_Municipality"] = "Municipio",
        ["Sighting_Review_Images_One"] = "1 photo",
        ["Sighting_Review_Images_Many"] = "{0} photos",
        ["Sighting_Review_Approve"] = "Approve",
        ["Sighting_Review_Deny"] = "Deny",
        ["Sighting_Review_Unapprove"] = "Back to pending",
        ["Sighting_Review_Approve_Title"] = "Approve this sighting?",
        ["Sighting_Review_Deny_Title"] = "Deny this sighting?",
        ["Sighting_Review_Approve_Effect"] = "Approving publishes this report to the catalogue: the species' last-seen date moves to the observation date, the species is linked to the municipio, and a generalized location circle appears on its map. The exact point stays visible only to the organization.",
        ["Sighting_Review_Reason"] = "Reason",
        ["Sighting_Review_Reason_Optional_Hint"] = "Optional. The reporter will see it.",
        ["Sighting_Review_Reason_Required_Hint"] = "Required. The reporter will see it.",
        ["Sighting_Review_Working"] = "Saving…",
        ["Sighting_Review_Done_Approved"] = "Sighting approved.",
        ["Sighting_Review_Done_Denied"] = "Sighting denied.",
        ["Sighting_Review_Done_Pending"] = "Sighting sent back to pending.",
        ["Sighting_Review_Error_Forbidden"] = "Your role no longer has permission to review sightings.",
        ["Sighting_Review_Error_NotFound"] = "That sighting no longer exists.",
        ["Sighting_Review_NoAccess_Title"] = "You don't have access to this page",
        ["Sighting_Review_NoAccess_Body"] = "Reviewing sightings needs a permission your role doesn't include. Ask an administrator of the organization to grant it.",
        ["Sighting_Review_NoAccess_Back"] = "Back to the map",
    };

    private static readonly Dictionary<string, string> Es = new(StringComparer.Ordinal)
    {
        ["Common_Loading"] = "Cargando…",
        ["Common_Cancel"] = "Cancelar",
        ["Common_Apply"] = "Aplicar",
        ["Common_Close"] = "Cerrar",
        ["Common_Back"] = "Atrás",
        ["Common_ViewDetails"] = "Ver detalles",
        ["Common_ViewAll"] = "Ver todos",
        ["Common_Search"] = "Buscar",
        ["Common_Sort"] = "Ordenar",
        ["Common_Clear"] = "Limpiar",
        ["Common_SelectAll"] = "Seleccionar todos",
        ["Common_ClearAll"] = "Limpiar todos",
        ["Common_SearchOff"] = "Sin resultados",
        ["Common_Verified"] = "Verificado",

        ["Nav_Map"] = "Mapa",
        ["Nav_Browse"] = "Explorar",
        ["Nav_Species"] = "Especies",
        ["Nav_Municipios"] = "Municipios",
        ["Nav_Categories"] = "Categorías",
        ["Nav_Practices"] = "Prácticas",
        ["Nav_Actions"] = "Acciones",

        ["Rail_Heading"] = "Libreta de campo",
        ["Rail_Tab_Municipios"] = "Municipios",
        ["Rail_Tab_Taxa"] = "Taxones",
        ["Rail_Empty"] = "Todavía no hay registros.",
        ["Rail_Collapse"] = "Cerrar la libreta",
        ["Rail_Expand"] = "Abrir la libreta",
        ["Shell_Search"] = "Buscar especies y municipios",
        ["Shell_Search_Searching"] = "Buscando…",
        ["Shell_Search_Empty"] = "No se encontró nada para «{0}».",
        ["Shell_Search_Clear"] = "Borrar la búsqueda",

        ["Browse_PageTitle"] = "Explorar",
        ["Browse_Eyebrow"] = "Referencia · Puerto Rico",
        ["Browse_Heading"] = "El catálogo detrás del mapa.",
        ["Browse_Lede"] = "Tres formas de entrar al mismo registro: por lo que es una especie, por el trabajo de conservación que la protege y por las acciones de recuperación que ese trabajo ejecuta.",
        ["Browse_Categories_Desc"] = "Todos los grupos taxonómicos registrados en la isla, con las especies catalogadas en cada uno.",
        ["Browse_Practices_Desc"] = "Prácticas de conservación del NRCS, cada una emparejada con las acciones que conlleva.",
        ["Browse_Actions_Desc"] = "Acciones de recuperación del Servicio de Pesca y Vida Silvestre, y las prácticas que las ejecutan.",
        ["Browse_Count_Pending"] = "—",
        ["Theme_ToDark"] = "Cambiar a oscuro",
        ["Theme_ToLight"] = "Cambiar a claro",

        ["Rail_Tab_Saved"] = "Guardadas",
        ["Rail_Tab_Nearby"] = "Cerca de mí",
        ["Rail_Saved_Empty"] = "Marca una especie o municipio para guardarlo aquí.",
        ["Rail_Nearby_Empty"] = "No hay registros a menos de {0} km.",
        ["Rail_Nearby_Prompt"] = "Usar mi ubicación",
        ["Rail_Nearby_Locating"] = "Buscándote…",
        ["Rail_Nearby_Denied"] = "No se concedió permiso de ubicación.",
        ["Rail_Nearby_Unsupported"] = "Este navegador no puede compartir la ubicación.",
        ["Rail_Nearby_Origin"] = "A menos de {0} km de ti",
        ["Rail_Distance_M"] = "{0} m",
        ["Rail_Distance_Km"] = "{0} km",
        ["Notebook_Save"] = "Guardar en la libreta",
        ["SpeciesDetail_Report"] = "Descargar informe PDF",
        ["Notebook_Unsave"] = "Quitar de la libreta",
        ["Notebook_Saved"] = "Guardada",
        ["Time_JustNow"] = "ahora mismo",
        ["Time_MinutesAgo"] = "hace {0} min",
        ["Time_HoursAgo"] = "hace {0} h",
        ["Time_DaysAgo"] = "hace {0} d",

        ["Hero_Eyebrow"] = "Volumen 03 · Atlas Viviente",
        ["Hero_LastSync"] = "Última sincronización · {0}",

        ["Species_PageTitle"] = "FaunaFinder — Especies",
        ["Species_Hero_HeadingLead"] = "Especies de",
        ["Species_Hero_HeadingTail"] = ", catalogadas y observadas.",
        ["Species_Hero_Lede"] = "Una guía de campo viva de la flora y fauna de la isla — construida con avistamientos verificados en los 78 municipios. Explora por taxón, estado de conservación o hábitat; sigue cualquier registro hasta su mapa de distribución y observaciones originales.",
        ["Species_Hero_RecordsLine"] = "{0} registros · {1} municipios",
        ["Species_Hero_UpdatedDaily"] = "Actualizado a diario",
        ["Species_Hero_RecordsPending"] = "— registros · — municipios",

        ["Species_Stats_Total_Label"] = "Total de especies",
        ["Species_Stats_Total_Sub_Delta"] = "{0} este trimestre",
        ["Species_Stats_Total_Sub_None"] = "—",
        ["Species_Stats_Endemic_Label"] = "Endémicas de P.R.",
        ["Species_Stats_Endemic_Sub"] = "{0}% del catálogo",
        ["Species_Stats_Threatened_Label"] = "Amenazadas · VU–CR",
        ["Species_Stats_Threatened_Sub_Delta"] = "{0} reclasificadas",
        ["Species_Stats_Municipios_Label"] = "Municipios cubiertos",
        ["Species_Stats_Municipios_Sub"] = "{0}% de {1} municipios + {2} Islas Vírgenes",

        ["Species_Featured_Heading"] = "Destacadas esta semana",
        ["Species_Featured_Meta"] = "Curado · actualizado los lunes",

        ["Species_Toolbar_Heading"] = "Encuentra lo que buscas",
        ["Species_Toolbar_RecordsMeta"] = "{0} registros · {1} municipios",
        ["Species_Toolbar_RecordsMeta_Loading"] = "Cargando catálogo…",
        ["Species_Toolbar_SearchPlaceholder"] = "Busca por nombre común, nombre científico o especie…",
        ["Species_Toolbar_Counter_Of"] = "de {0}",
        ["Species_Toolbar_Sort_Prefix"] = "Orden:",
        ["Species_Toolbar_Sort_ScientificAsc"] = "Nombre científico ↑",
        ["Species_Toolbar_Sort_ScientificDesc"] = "Nombre científico ↓",
        ["Species_Toolbar_Sort_Recent"] = "Observadas recientemente",
        ["Species_Toolbar_Sort_MostWidespread"] = "Más extendidas",

        ["Species_Chip_Taxon"] = "Taxón: {0}",
        ["Species_Chip_Status"] = "Estado: {0}",
        ["Species_Chip_Endemic"] = "Solo endémicas",
        ["Species_Chip_ObservedRecently"] = "Observadas en los últimos 12 meses",
        ["Species_Chip_HasPhoto"] = "Con foto",
        ["Species_Chip_MinMunicipios"] = "≥ {0} municipios",

        ["Species_Filter_Heading"] = "Refinar el catálogo",
        ["Species_Filter_TotalRecords"] = "{0} registros",
        ["Species_Filter_Section_Taxa"] = "Grupo taxonómico",
        ["Species_Filter_Section_Status"] = "Estado de conservación (UICN)",
        ["Species_Filter_Section_Qualifiers"] = "Criterios",
        ["Species_Filter_Section_MinMunicipios"] = "Mínimo de municipios",
        ["Species_Filter_Qualifier_EndemicLabel"] = "Solo endémicas de Puerto Rico",
        ["Species_Filter_Qualifier_ObservedLabel"] = "Observadas en los últimos 12 meses",
        ["Species_Filter_Qualifier_HasPhotoLabel"] = "Con foto",
        ["Species_Filter_StatusMeta_Selected"] = "{0} seleccionadas",
        ["Species_Filter_MinMunicipios_Meta"] = "≥ {0}",
        ["Species_Filter_MinMunicipios_Rare"] = "1 (raras)",
        ["Species_Filter_MinMunicipios_Ubiquitous"] = "78 (ubicuas)",
        ["Species_Filter_Reset"] = "Restablecer filtros",

        ["Species_Taxa_Bird"] = "Ave",
        ["Species_Taxa_Plant"] = "Planta",
        ["Species_Taxa_Reptile"] = "Reptil",
        ["Species_Taxa_Amphib"] = "Anfibio",
        ["Species_Taxa_Fish"] = "Pez",
        ["Species_Taxa_Mammal"] = "Mamífero",
        ["Species_Taxa_Invert"] = "Invertebrado",
        ["Species_Taxa_Fungi"] = "Hongo",

        ["Species_Iucn_LC"] = "Preocupación menor",
        ["Species_Iucn_NT"] = "Casi amenazada",
        ["Species_Iucn_VU"] = "Vulnerable",
        ["Species_Iucn_EN"] = "En peligro",
        ["Species_Iucn_CR"] = "En peligro crítico",
        ["Species_Iucn_DD"] = "Datos insuficientes",
        ["Species_Iucn_EX"] = "Extinta",

        ["Species_Card_Municipios"] = "{0} municipios",
        ["Species_Card_EndemicBadge"] = "Endémica PR",
        ["Species_Grid_LoadingMore"] = "Cargando más registros…",
        ["Species_Grid_LoadMore"] = "Cargar más registros",
        ["Species_Grid_EndOfCatalogue"] = "— fin del catálogo —",
        ["Species_Grid_Empty_Title"] = "Sin coincidencias",
        ["Species_Grid_Empty_Description"] = "Ajusta los filtros o los términos de búsqueda.",

        ["Time_MinutesAgo"] = "hace {0} min",
        ["Time_HoursAgo"] = "hace {0} h",
        ["Time_DaysAgo"] = "hace {0} d",
        ["Time_MonthsAgo"] = "hace {0} meses",
        ["Time_YearsAgo"] = "hace {0} años",

        ["SpeciesDetail_Rank_Global"] = "Global: {0}",
        ["SpeciesDetail_Rank_State"] = "Estatal: {0}",
        ["SpeciesDetail_Kingdom_Fauna"] = "Fauna",
        ["SpeciesDetail_Kingdom_Flora"] = "Flora",
        ["SpeciesDetail_ElCode"] = "Código de elemento: {0}",
        ["SpeciesDetail_Categories_Heading"] = "Categorías",
        ["SpeciesDetail_Municipalities_Heading"] = "Municipios",
        ["SpeciesDetail_Municipalities_Empty_Title"] = "Sin municipios",
        ["SpeciesDetail_Municipalities_Empty_Description"] = "Esta especie aún no tiene municipios asociados.",
        ["SpeciesDetail_NotFound_Title"] = "Especie no encontrada",
        ["SpeciesDetail_NotFound_Description"] = "La especie que buscas no existe o fue eliminada.",

        ["Muni_PageTitle"] = "FaunaFinder — Municipios",
        ["Muni_Hero_HeadingLead"] = "Municipios de",
        ["Muni_Hero_HeadingTail"] = ", en el mapa y observados.",
        ["Muni_Hero_Lede"] = "Un índice geográfico de los 78 municipios de Puerto Rico — cada uno anotado con las especies registradas dentro de sus límites. Busca por nombre, ordena por biodiversidad, o toca un pin para abrir el registro completo del municipio y sus residentes más destacados.",
        ["Muni_Hero_RecordsLine"] = "{0} municipios · {1} registros",
        ["Muni_Hero_RecordsPending"] = "— municipios · — registros",
        ["Muni_Hero_Hint"] = "Toca un pin o una fila para profundizar",

        ["Muni_Stats_Total_Label"] = "Total de municipios",
        ["Muni_Stats_Total_Unit"] = "/ {0} rastreados",
        ["Muni_Stats_Total_Sub"] = "{0} municipios + {1} Islas Vírgenes de EE. UU.",
        ["Muni_Stats_Species_Label"] = "Especies catalogadas",
        ["Muni_Stats_Species_Sub"] = "en toda la isla",
        ["Muni_Stats_Avg_Label"] = "Prom · especies / municipio",
        ["Muni_Stats_Avg_Sub"] = "{0} municipios aportan",
        ["Muni_Stats_Hotspots_Label"] = "Focos endémicos",
        ["Muni_Stats_Hotspots_Sub"] = "≥ 10 especies endémicas presentes",

        ["Muni_Tab_Map"] = "Mapa",
        ["Muni_Tab_List"] = "Lista",

        ["Muni_List_SearchPlaceholder"] = "Busca municipios por nombre…",
        ["Muni_List_VisibleAll"] = "{0} municipios",
        ["Muni_List_VisibleFiltered"] = "{0} de {1}",
        ["Muni_List_Loading"] = "Cargando…",
        ["Muni_List_Sort_SpeciesCountDesc"] = "cantidad de especies ↓",
        ["Muni_List_Sort_NameAsc"] = "nombre A–Z",
        ["Muni_List_Sort_Prefix"] = "Orden:",
        ["Muni_List_Empty"] = "Ningún municipio coincide con \"{0}\"",
        ["Muni_List_Foot_Loading"] = "cargando municipios",
        ["Muni_List_Foot_Total"] = "{0} municipios rastreados",

        ["Muni_Map_Legend_Title"] = "Municipios",
        ["Muni_Map_Legend_Selected"] = "Seleccionado",
        ["Muni_Map_Legend_Boundary"] = "Límite",
        ["Muni_DetailCard_Species_Label"] = "Especies",
        ["Muni_DetailCard_Fips_Label"] = "FIPS",
        ["Muni_DetailCard_CountRecorded"] = "{0} especies registradas",
        ["Muni_DetailCard_CountPending"] = "Conteo pendiente",
        ["Muni_Card_SpeciesCount"] = "{0} especies",

        ["MuniDetail_Subline"] = "{0} · FIPS {1}",
        ["MuniDetail_Centroid"] = "Centroide · {0}″N {1}″O",
        ["MuniDetail_Species_Heading"] = "Especies",
        ["MuniDetail_Species_Empty_Title"] = "Sin especies",
        ["MuniDetail_Species_Empty_Description"] = "Aún no se han asociado especies con este municipio.",
        ["MuniDetail_NotFound_Title"] = "Municipio no encontrado",
        ["MuniDetail_NotFound_Description"] = "El municipio que buscas no existe o fue eliminado.",

        ["Categories_PageTitle"] = "Categorías",
        ["Categories_Empty_Title"] = "Sin categorías",
        ["Categories_Empty_Description"] = "Aún no se han creado categorías de especies.",
        ["CategoryDetail_SpeciesCount"] = "{0} especies",
        ["CategoryDetail_Empty_Title"] = "Sin especies",
        ["CategoryDetail_Empty_Description"] = "Aún no se ha categorizado ninguna especie aquí.",

        ["Practices_PageTitle"] = "Prácticas",
        ["Practices_Hero_HeadingLead"] = "Conservación en",
        ["Practices_Hero_HeadingTail"] = ", práctica por práctica.",
        ["Practices_Hero_Lede"] = "Las prácticas de conservación del NRCS detrás del trabajo de recuperación de la isla — cada una emparejada con las acciones del Servicio de Pesca y Vida Silvestre que conlleva y las especies que esas acciones protegen. Abre una práctica para leer sus acciones y sigue cualquiera hasta las especies a las que aplica.",
        ["Practices_Hero_RecordsLine"] = "{0} prácticas catalogadas",
        ["Practices_Hero_RecordsPending"] = "— prácticas catalogadas",
        ["Practices_Hero_Hint"] = "Toca una práctica para ver sus acciones",
        ["Practices_Empty_Title"] = "Sin prácticas",
        ["Practices_Empty_Description"] = "Aún no se han cargado prácticas de conservación del NRCS.",
        ["PracticeDetail_Subline"] = "Práctica de conservación del NRCS",
        ["PracticeDetail_Actions_Heading"] = "Acciones del FWS",
        ["PracticeDetail_Actions_Empty_Title"] = "Sin acciones",
        ["PracticeDetail_Actions_Empty_Description"] = "Aún no hay acciones del FWS vinculadas a esta práctica.",
        ["PracticeDetail_ActionCode"] = "FWS {0}",
        ["PracticeDetail_ActionSpeciesCount"] = "{0} especies",
        ["PracticeDetail_Species_Heading"] = "Especies",
        ["PracticeDetail_SpeciesCount"] = "{0} especies",
        ["PracticeDetail_Empty_Title"] = "Sin especies",
        ["PracticeDetail_Empty_Description"] = "Aún no hay especies vinculadas a esta práctica de conservación.",

        ["Actions_PageTitle"] = "Acciones",
        ["Actions_Hero_HeadingLead"] = "Lo que la recuperación le pide a",
        ["Actions_Hero_HeadingTail"] = ", acción por acción.",
        ["Actions_Hero_Lede"] = "Las acciones del Servicio de Pesca y Vida Silvestre que dan forma a la recuperación de la isla — cada una ejecutada mediante las prácticas de conservación del NRCS que la financian y la llevan al campo. Abre una acción para ver qué prácticas la cumplen y las especies para las que fue escrita.",
        ["Actions_Hero_RecordsLine"] = "{0} acciones catalogadas",
        ["Actions_Hero_RecordsPending"] = "— acciones catalogadas",
        ["Actions_Hero_Hint"] = "Toca una acción para ver sus prácticas",
        ["Actions_Empty_Title"] = "Sin acciones",
        ["Actions_Empty_Description"] = "Aún no se han cargado acciones de conservación del FWS.",
        ["ActionDetail_Subline"] = "Acción de conservación del FWS",
        ["ActionDetail_Practices_Heading"] = "Prácticas de conservación",
        ["ActionDetail_Practices_Empty_Title"] = "Sin prácticas",
        ["ActionDetail_Practices_Empty_Description"] = "Aún no hay prácticas de conservación del NRCS vinculadas a esta acción.",
        ["ActionDetail_PracticeCode"] = "NRCS {0}",
        ["ActionDetail_PracticeSpeciesCount"] = "{0} especies",
        ["ActionDetail_Species_Heading"] = "Especies",
        ["ActionDetail_SpeciesCount"] = "{0} especies",
        ["ActionDetail_Empty_Title"] = "Sin especies",
        ["ActionDetail_Empty_Description"] = "Aún no hay especies vinculadas a esta acción de conservación.",

        ["Home_SidebarEmpty"] = "Toca un municipio para ver sus especies",
        ["Map_Panel_Eyebrow"] = "Municipio",
        ["Map_Panel_NoSpecies_Title"] = "Sin especies registradas",
        ["Map_Panel_NoSpecies_Description"] = "Aún no se han observado especies en este municipio.",
        ["Map_Panel_SpeciesObserved"] = "{0} especies observadas",
        ["Map_NearMe_Label"] = "Especies cerca de mí",
        ["Map_NearMe_Title"] = "Cerca de mí",
        ["Map_NearMe_Eyebrow"] = "En un radio de {0} km",
        ["Map_DrawArea_Label"] = "Dibujar área",
        ["Map_DrawArea_Title"] = "Área dibujada",
        ["Map_DrawArea_Eyebrow"] = "Búsqueda personalizada",
        ["Map_Draw_Instructions"] = "Haz clic en el mapa para agregar puntos. Doble clic, Enter o clic en el primer punto para terminar. Esc cancela.",
        ["Map_Draw_Finish"] = "Terminar",
        ["Map_Draw_Cancel"] = "Cancelar",
        ["Map_Heatmap_Show"] = "Mapa de calor",
        ["Map_Heatmap_Hide"] = "Ocultar mapa de calor",
        ["Map_Heatmap_All"] = "Todas",
        ["Map_Heatmap_Fauna"] = "Fauna",
        ["Map_Heatmap_Flora"] = "Flora",
        ["Map_Travel_Label"] = "Viajar a otra región",
        ["Map_Travel_Title"] = "Viajar a…",
        ["Map_Region_PuertoRico"] = "Puerto Rico",
        ["Map_Region_PuertoRico_Subtitle"] = "78 municipios",
        ["Map_Region_VirginIslands"] = "Islas Vírgenes de EE. UU.",
        ["Map_Region_VirginIslands_Subtitle"] = "3 islas",
        ["Map_Nearby_Empty_Title"] = "No se encontraron especies",
        ["Map_Nearby_Empty_Description"] = "No hay ubicaciones de especies registradas en esta área.",
        ["Map_Nearby_Count"] = "{0} especies encontradas",
        ["Map_Location_Unnamed"] = "Ubicación sin nombre",
        ["Map_Location_RadiusMeters"] = "{0} m de radio",
        ["Map_ViewDetails"] = "Detalles",
        ["Map_ViewLocations"] = "Ver en el mapa",
        ["Map_Geolocation_Denied"] = "Se denegó el permiso de ubicación. Actívalo en tu navegador para buscar cerca de ti.",
        ["Map_Geolocation_Unavailable"] = "No se pudo determinar tu ubicación. Inténtalo de nuevo.",
        ["Map_Geolocation_Unsupported"] = "Tu navegador no es compatible con la geolocalización.",
        ["Map_NoLocations_ForSpecies"] = "Esta especie aún no tiene ubicaciones registradas.",
        ["Map_Filter_Title"] = "Filtros",
        ["Map_Filter_Label"] = "Filtrar por práctica de conservación",
        ["Map_Filter_NrcsPractices"] = "Prácticas NRCS",
        ["Map_Filter_FwsActions"] = "Acciones FWS",
        ["Map_Filter_ClearAll"] = "Limpiar todo",
        ["Map_Filter_Apply"] = "Aplicar",
        ["Map_Filter_Showing"] = "Mostrando {0} de {1} especies",

        ["Auth_SignIn"] = "Iniciar sesión",
        ["Auth_SignOut"] = "Cerrar sesión",
        ["Auth_SigningIn"] = "Iniciando sesión…",
        ["Auth_CreateAccount"] = "Crear cuenta",
        ["Auth_CreatingAccount"] = "Creando tu cuenta…",
        ["Auth_AccountLabel"] = "Cuenta",
        ["Auth_WelcomeBack"] = "Hola de nuevo",
        ["Auth_JoinTitle"] = "Únete a FaunaFinder",
        ["Auth_Email"] = "Correo electrónico",
        ["Auth_Password"] = "Contraseña",
        ["Auth_ConfirmPassword"] = "Confirmar contraseña",
        ["Auth_DisplayName"] = "Nombre",
        ["Auth_StudentQuestion"] = "¿Eres estudiante de la Inter Metro?",
        ["Auth_Yes"] = "Sí",
        ["Auth_No"] = "No",
        ["Auth_NoAccount"] = "¿No tienes cuenta?",
        ["Auth_HaveAccount"] = "¿Ya tienes cuenta?",
        ["Auth_Request_Pending"] = "Acceso de estudiante: pendiente de aprobación",
        ["Auth_Request_Approved"] = "Acceso de estudiante: aprobado",
        ["Auth_Request_Rejected"] = "Acceso de estudiante: no aprobado",
        ["Auth_RequestNotSubmitted"] = "Tu cuenta fue creada, pero no se pudo enviar la solicitud de acceso de estudiante. Inténtalo más tarde.",
        ["Auth_ServerUnreachable"] = "No se pudo conectar con el servidor. Inténtalo de nuevo.",
        ["Auth_SignInFailed"] = "Algo salió mal al iniciar sesión. Inténtalo de nuevo.",
        ["Auth_SignUpFailed"] = "Algo salió mal al crear tu cuenta. Inténtalo de nuevo.",

        ["Sighting_Report_PageTitle"] = "Reportar un avistamiento",
        ["Sighting_Report_Title"] = "Reportar avistamiento",
        ["Sighting_Report_Action"] = "Reportar avistamiento",
        ["Sighting_Report_Lede"] = "Cuéntanos qué viste y dónde. Un revisor de FaunaFinder verifica cada reporte antes de añadirlo al catálogo.",
        ["Sighting_Species"] = "Especie",
        ["Sighting_Species_Placeholder"] = "Busca por nombre común o científico",
        ["Sighting_Species_NoResults"] = "Ninguna especie coincide con esa búsqueda.",
        ["Sighting_Species_Required"] = "Selecciona la especie que viste.",
        ["Sighting_Location"] = "Ubicación",
        ["Sighting_Location_Hint"] = "Toca el mapa para colocar el marcador o usa tu ubicación.",
        ["Sighting_Location_Required"] = "Coloca el marcador donde lo viste.",
        ["Sighting_UseMyLocation"] = "Usar mi ubicación",
        ["Sighting_Municipality_Resolving"] = "Buscando el municipio…",
        ["Sighting_Municipality_Outside"] = "Fuera de todo municipio",
        ["Sighting_Municipality_Unknown"] = "No se pudo determinar el municipio",
        ["Sighting_ObservedAt"] = "Observado",
        ["Sighting_ObservedDate"] = "Fecha del avistamiento",
        ["Sighting_ObservedTime"] = "Hora del avistamiento",
        ["Sighting_ObservedAt_Required"] = "Indica cuándo lo viste.",
        ["Sighting_Count"] = "Cantidad",
        ["Sighting_Count_Hint"] = "Opcional. Número de individuos que viste.",
        ["Sighting_Count_Value"] = "Cantidad: {0}",
        ["Sighting_Note"] = "Nota",
        ["Sighting_Note_Hint"] = "Opcional. Comportamiento, hábitat, cualquier detalle que ayude al revisor.",
        ["Sighting_Submit"] = "Enviar reporte",
        ["Sighting_Submitting"] = "Enviando…",
        ["Sighting_Unavailable"] = "El reporte de avistamientos no está disponible por el momento. Inténtalo de nuevo en un rato.",
        ["Sighting_Report_Success"] = "¡Gracias! Tu avistamiento fue enviado para revisión.",
        ["Sighting_Error_Unreachable"] = "No se pudo conectar con el servidor. Inténtalo de nuevo.",
        ["Sighting_Error_SignedOut"] = "Tu sesión terminó. Inicia sesión de nuevo.",
        ["Sighting_Error_Forbidden"] = "No tienes permiso para hacer eso.",
        ["Sighting_Error_NotFound"] = "Ese avistamiento o esa especie ya no existe.",
        ["Sighting_Error_TooMany"] = "Demasiadas solicitudes. Espera un momento e inténtalo de nuevo.",
        ["Sighting_Error_Generic"] = "Algo salió mal. Inténtalo de nuevo.",
        ["Sighting_Mine_PageTitle"] = "Mis avistamientos",
        ["Sighting_Mine_Title"] = "Mis avistamientos",
        ["Sighting_Mine_Lede"] = "Todo lo que has reportado, de lo más reciente a lo más antiguo, con el estado de cada reporte.",
        ["Sighting_Mine_Empty_Title"] = "Aún no hay avistamientos",
        ["Sighting_Mine_Empty_Description"] = "¿Viste algo? Repórtalo y aparecerá aquí.",
        ["Sighting_Status_Pending"] = "Pendiente",
        ["Sighting_Status_Approved"] = "Aprobado",
        ["Sighting_Status_Denied"] = "Denegado",
        ["Sighting_Coordinates"] = "Coordenadas",
        ["Sighting_ReportedAt"] = "Reportado",
        ["Sighting_Photos"] = "Fotos",
        ["Sighting_Review"] = "Revisión",
        ["Sighting_ReviewedBy"] = "Revisado por {0} el {1}",
        ["Sighting_Notes"] = "Notas",
        ["Sighting_Notes_Empty"] = "Aún no hay notas. Los revisores pueden hacer preguntas aquí.",
        ["Sighting_Note_Add"] = "Añadir una nota",
        ["Sighting_Note_Send"] = "Enviar",
        ["Sighting_Image_Add"] = "Añadir fotos",
        ["Sighting_Image_Hint"] = "Hasta 5 fotos de 10 MB cada una (JPEG, PNG o WebP).",
        ["Sighting_Image_Empty"] = "Aún no hay fotos.",
        ["Sighting_Image_TooMany"] = "Puedes adjuntar hasta {0} fotos.",
        ["Sighting_Image_TooLarge"] = "{0} pesa más de 10 MB.",
        ["Sighting_Image_NotImage"] = "{0} no es una imagen.",
        ["Sighting_Image_UploadFailed"] = "No se pudo subir {0}.",
        ["Sighting_Image_Uploading"] = "Subiendo fotos…",
        ["Sighting_Image_View"] = "Ver foto",
        ["Sighting_Image_Close"] = "Cerrar foto",
        ["Sighting_Image_Delete"] = "Eliminar foto",
        ["Sighting_Image_Delete_Confirm"] = "¿Eliminar esta foto? No se puede deshacer.",
        ["Sighting_Image_DeleteFailed"] = "No se pudo eliminar la foto.",
        ["Sighting_Review_Nav"] = "Revisar avistamientos",
        ["Sighting_Review_PageTitle"] = "Revisar avistamientos",
        ["Sighting_Review_Title"] = "Revisar avistamientos",
        ["Sighting_Review_Lede"] = "Avistamientos reportados a {0}. Al aprobar uno, pasa a formar parte del catálogo.",
        ["Sighting_Review_Filter_Species"] = "Filtrar por especie",
        ["Sighting_Review_Empty_Title"] = "Nada por aquí",
        ["Sighting_Review_Empty_Pending"] = "No hay avistamientos pendientes. Los reportes nuevos aparecerán aquí.",
        ["Sighting_Review_Empty_Approved"] = "Ningún avistamiento aprobado coincide con este filtro.",
        ["Sighting_Review_Empty_Denied"] = "Ningún avistamiento denegado coincide con este filtro.",
        ["Sighting_Review_LoadMore"] = "Cargar más",
        ["Sighting_Review_ReportedBy"] = "Reportado por {0}",
        ["Sighting_Review_Reporter"] = "Reportado por",
        ["Sighting_Review_Municipality"] = "Municipio",
        ["Sighting_Review_Images_One"] = "1 foto",
        ["Sighting_Review_Images_Many"] = "{0} fotos",
        ["Sighting_Review_Approve"] = "Aprobar",
        ["Sighting_Review_Deny"] = "Denegar",
        ["Sighting_Review_Unapprove"] = "Devolver a pendiente",
        ["Sighting_Review_Approve_Title"] = "¿Aprobar este avistamiento?",
        ["Sighting_Review_Deny_Title"] = "¿Denegar este avistamiento?",
        ["Sighting_Review_Approve_Effect"] = "Al aprobar, este reporte se publica en el catálogo: la fecha del último avistamiento de la especie pasa a ser la de la observación, la especie queda enlazada al municipio y aparece un círculo de ubicación generalizado en su mapa. El punto exacto solo lo ve la organización.",
        ["Sighting_Review_Reason"] = "Razón",
        ["Sighting_Review_Reason_Optional_Hint"] = "Opcional. La persona que reportó la verá.",
        ["Sighting_Review_Reason_Required_Hint"] = "Requerida. La persona que reportó la verá.",
        ["Sighting_Review_Working"] = "Guardando…",
        ["Sighting_Review_Done_Approved"] = "Avistamiento aprobado.",
        ["Sighting_Review_Done_Denied"] = "Avistamiento denegado.",
        ["Sighting_Review_Done_Pending"] = "El avistamiento volvió a pendiente.",
        ["Sighting_Review_Error_Forbidden"] = "Tu rol ya no tiene permiso para revisar avistamientos.",
        ["Sighting_Review_Error_NotFound"] = "Ese avistamiento ya no existe.",
        ["Sighting_Review_NoAccess_Title"] = "No tienes acceso a esta página",
        ["Sighting_Review_NoAccess_Body"] = "Para revisar avistamientos hace falta un permiso que tu rol no incluye. Pídele a un administrador de la organización que lo conceda.",
        ["Sighting_Review_NoAccess_Back"] = "Volver al mapa",
    };
}
