// <auto-generated />
using System;
using EcoData.Wildlife.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoData.Wildlife.Database.Migrations
{
    [DbContext(typeof(WildlifeDbContext))]
    [Migration("20260902001420_AddSightings")]
    partial class AddSightings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.FwsAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_fws_actions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("fws_actions_code_uidx");

                    b.ToTable("fws_actions", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.FwsLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FwsActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("fws_action_id");

                    b.Property<Guid>("NrcsPracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("nrcs_practice_id");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_fws_links");

                    b.HasIndex("FwsActionId")
                        .HasDatabaseName("ix_fws_links_fws_action_id");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_fws_links_species_id");

                    b.HasIndex("NrcsPracticeId", "FwsActionId", "SpeciesId")
                        .HasDatabaseName("fws_links_practice_action_species_idx");

                    b.ToTable("fws_links", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.MunicipalitySpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_municipality_species");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("municipality_species_municipality_id_idx");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_municipality_species_species_id");

                    b.HasIndex("MunicipalityId", "SpeciesId")
                        .IsUnique()
                        .HasDatabaseName("municipality_species_municipality_species_uidx");

                    b.ToTable("municipality_species", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.NrcsPractice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_nrcs_practices");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("nrcs_practices_code_uidx");

                    b.ToTable("nrcs_practices", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.Sighting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IndividualCount")
                        .HasColumnType("integer")
                        .HasColumnName("individual_count");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ReporterDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reporter_display_name");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_reason");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by_display_name");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sightings");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("sightings_species_id_ix");

                    b.HasIndex("ReporterUserId", "Id")
                        .HasDatabaseName("sightings_reporter_ix");

                    b.HasIndex("OrganizationId", "Status", "Id")
                        .HasDatabaseName("sightings_org_status_ix");

                    b.ToTable("sightings", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SightingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blob_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SightingId")
                        .HasColumnType("uuid")
                        .HasColumnName("sighting_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("UploadedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("uploaded_by_display_name");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_sighting_images");

                    b.HasIndex("SightingId", "Id")
                        .HasDatabaseName("sighting_images_sighting_ix");

                    b.ToTable("sighting_images", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SightingNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_display_name");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SightingId")
                        .HasColumnType("uuid")
                        .HasColumnName("sighting_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_sighting_notes");

                    b.HasIndex("SightingId", "Id")
                        .HasDatabaseName("sighting_notes_sighting_ix");

                    b.ToTable("sighting_notes", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ElCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("el_code");

                    b.Property<string>("EndemicStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("endemic_status");

                    b.Property<string>("GRank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("g_rank");

                    b.Property<string>("Habitat")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("habitat");

                    b.Property<string>("ImageSourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_source_url");

                    b.Property<bool>("IsFauna")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fauna");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("IucnStatus")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("iucn_status");

                    b.Property<DateTimeOffset?>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_image_content_type");

                    b.Property<byte[]>("ProfileImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_image_data");

                    b.Property<string>("SRank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("s_rank");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("EndemicStatus")
                        .HasDatabaseName("species_endemic_status_ix");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("species_is_featured_ix")
                        .HasFilter("is_featured = true");

                    b.HasIndex("IucnStatus")
                        .HasDatabaseName("species_iucn_status_ix");

                    b.HasIndex("ScientificName")
                        .IsUnique()
                        .HasDatabaseName("species_scientific_name_uidx");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_species_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("species_categories_code_uidx");

                    b.ToTable("species_categories", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesCategoryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_category_links");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_species_category_links_category_id");

                    b.HasIndex("SpeciesId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("species_category_links_species_category_uidx");

                    b.ToTable("species_category_links", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_locations");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("species_locations_species_id_ix");

                    b.ToTable("species_locations", (string)null);
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.FwsAction", b =>
                {
                    b.OwnsMany("EcoData.Common.i18n.LocaleValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("FwsActionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("FwsActionId", "__synthesizedOrdinal");

                            b1.ToTable("fws_actions");

                            b1.ToJson("name");

                            b1.WithOwner()
                                .HasForeignKey("FwsActionId")
                                .HasConstraintName("fk_fws_actions_fws_actions_fws_action_id");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.FwsLink", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.FwsAction", "FwsAction")
                        .WithMany("FwsLinks")
                        .HasForeignKey("FwsActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_fws_actions_fws_action_id");

                    b.HasOne("EcoData.Wildlife.Database.Models.NrcsPractice", "NrcsPractice")
                        .WithMany("FwsLinks")
                        .HasForeignKey("NrcsPracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_nrcs_practices_nrcs_practice_id");

                    b.HasOne("EcoData.Wildlife.Database.Models.Species", "Species")
                        .WithMany("FwsLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fws_links_species_species_id");

                    b.OwnsMany("EcoData.Common.i18n.LocaleValue", "Justification", b1 =>
                        {
                            b1.Property<Guid>("FwsLinkId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("FwsLinkId", "__synthesizedOrdinal");

                            b1.ToTable("fws_links");

                            b1.ToJson("justification");

                            b1.WithOwner()
                                .HasForeignKey("FwsLinkId")
                                .HasConstraintName("fk_fws_links_fws_links_fws_link_id");
                        });

                    b.Navigation("FwsAction");

                    b.Navigation("Justification");

                    b.Navigation("NrcsPractice");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.MunicipalitySpecies", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.Species", "Species")
                        .WithMany("MunicipalitySpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipality_species_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.NrcsPractice", b =>
                {
                    b.OwnsMany("EcoData.Common.i18n.LocaleValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("NrcsPracticeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("NrcsPracticeId", "__synthesizedOrdinal");

                            b1.ToTable("nrcs_practices");

                            b1.ToJson("name");

                            b1.WithOwner()
                                .HasForeignKey("NrcsPracticeId")
                                .HasConstraintName("fk_nrcs_practices_nrcs_practices_nrcs_practice_id");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.Sighting", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.Species", "Species")
                        .WithMany("Sightings")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sightings_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SightingImage", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.Sighting", "Sighting")
                        .WithMany("Images")
                        .HasForeignKey("SightingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sighting_images_sightings_sighting_id");

                    b.Navigation("Sighting");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SightingNote", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.Sighting", "Sighting")
                        .WithMany("Notes")
                        .HasForeignKey("SightingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sighting_notes_sightings_sighting_id");

                    b.Navigation("Sighting");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.Species", b =>
                {
                    b.OwnsMany("EcoData.Common.i18n.LocaleValue", "CommonName", b1 =>
                        {
                            b1.Property<Guid>("SpeciesId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SpeciesId", "__synthesizedOrdinal")
                                .HasName("pk_species");

                            b1.ToTable("species");

                            b1.ToJson("common_name");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId")
                                .HasConstraintName("fk_species_species_species_id");
                        });

                    b.Navigation("CommonName");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesCategory", b =>
                {
                    b.OwnsMany("EcoData.Common.i18n.LocaleValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("SpeciesCategoryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SpeciesCategoryId", "__synthesizedOrdinal");

                            b1.ToTable("species_categories");

                            b1.ToJson("name");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesCategoryId")
                                .HasConstraintName("fk_species_categories_species_categories_species_category_id");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesCategoryLink", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.SpeciesCategory", "Category")
                        .WithMany("SpeciesLinks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_category_links_species_categories_category_id");

                    b.HasOne("EcoData.Wildlife.Database.Models.Species", "Species")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_category_links_species_species_id");

                    b.Navigation("Category");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesLocation", b =>
                {
                    b.HasOne("EcoData.Wildlife.Database.Models.Species", "Species")
                        .WithMany("Locations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_locations_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.FwsAction", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.NrcsPractice", b =>
                {
                    b.Navigation("FwsLinks");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.Sighting", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.Species", b =>
                {
                    b.Navigation("CategoryLinks");

                    b.Navigation("FwsLinks");

                    b.Navigation("Locations");

                    b.Navigation("MunicipalitySpecies");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("EcoData.Wildlife.Database.Models.SpeciesCategory", b =>
                {
                    b.Navigation("SpeciesLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
