// <auto-generated />
using System;
using EcoData.AquaTrack.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoData.AquaTrack.Database.Migrations
{
    [DbContext(typeof(AquaTrackDbContext))]
    [Migration("20260311030112_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<double?>("ThresholdMax")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_max");

                    b.Property<double?>("ThresholdMin")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_min");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_alerts_triggered_at");

                    b.HasIndex("SensorId", "Resolved")
                        .HasDatabaseName("ix_alerts_sensor_id_resolved");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_api_keys_organization_id");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("ix_api_keys_is_active_expires_at");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("PullIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("pull_interval_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_data_sources_organization_id");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<DateTimeOffset>("LastRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recorded_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_logs");

                    b.HasIndex("DataSourceId", "IngestedAt")
                        .HasDatabaseName("ix_ingestion_logs_data_source_id_ingested_at");

                    b.ToTable("ingestion_logs", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AboutUs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("about_us");

                    b.Property<string>("CardPictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("card_picture_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_picture_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_name");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_members_organization_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_organization_members_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_user_id_organization_id");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_roles");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_roles_organization_id_name");

                    b.ToTable("organization_roles", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.HasKey("RoleId", "Permission")
                        .HasName("pk_organization_role_permissions");

                    b.ToTable("organization_role_permissions", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.HasKey("Id")
                        .HasName("pk_parameters");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_parameters_code");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_parameters_sensor_type_id");

                    b.ToTable("parameters", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_readings");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_readings_recorded_at");

                    b.HasIndex("SensorId", "RecordedAt")
                        .HasDatabaseName("ix_readings_sensor_id_recorded_at");

                    b.HasIndex("SensorId", "Parameter", "RecordedAt")
                        .HasDatabaseName("ix_readings_sensor_id_parameter_recorded_at");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ReportingMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reporting_mode");

                    b.Property<Guid?>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_sensors_municipality_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_sensors_sensor_type_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_sensors_source_id");

                    b.HasIndex("OrganizationId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_organization_id_external_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorHealthAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alert_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_health_alerts");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_sensor_health_alerts_sensor_id");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_sensor_health_alerts_triggered_at");

                    b.HasIndex("SensorId", "ResolvedAt")
                        .HasDatabaseName("ix_sensor_health_alerts_sensor_id_resolved_at");

                    b.ToTable("sensor_health_alerts", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorHealthConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("expected_interval_seconds");

                    b.Property<bool>("IsMonitoringEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monitoring_enabled");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<int>("StaleThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("stale_threshold_seconds");

                    b.Property<int>("UnhealthyThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("unhealthy_threshold_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_health_configs");

                    b.HasIndex("SensorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_health_configs_sensor_id");

                    b.ToTable("sensor_health_configs", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorHealthStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset?>("LastReadingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reading_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_health_statuses");

                    b.HasIndex("SensorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_health_statuses_sensor_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sensor_health_statuses_status");

                    b.ToTable("sensor_health_statuses", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sensor_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_types_code");

                    b.ToTable("sensor_types", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Alert", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.ApiKey", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Organization", "Organization")
                        .WithMany("ApiKeys")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.DataSource", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Organization", "Organization")
                        .WithMany("DataSources")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_sources_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.IngestionLog", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_logs_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationMember", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");

                    b.HasOne("EcoData.AquaTrack.Database.Models.OrganizationRole", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organization_roles_role_id");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationRole", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_organization_roles_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationRolePermission", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.OrganizationRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_role_permissions_organization_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Parameter", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.SensorType", "SensorType")
                        .WithMany("Parameters")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parameters_sensor_types_sensor_type_id");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Reading", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Sensor", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Organization", "Organization")
                        .WithMany("Sensors")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_organizations_organization_id");

                    b.HasOne("EcoData.AquaTrack.Database.Models.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sensors_sensor_types_sensor_type_id");

                    b.HasOne("EcoData.AquaTrack.Database.Models.DataSource", "DataSource")
                        .WithMany("Sensors")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sensors_data_sources_source_id");

                    b.Navigation("DataSource");

                    b.Navigation("Organization");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorHealthAlert", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithMany("HealthAlerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_health_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorHealthConfig", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithOne("HealthConfig")
                        .HasForeignKey("EcoData.AquaTrack.Database.Models.SensorHealthConfig", "SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_health_configs_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorHealthStatus", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithOne("HealthStatus")
                        .HasForeignKey("EcoData.AquaTrack.Database.Models.SensorHealthStatus", "SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_health_statuses_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.DataSource", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Organization", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("DataSources");

                    b.Navigation("Members");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.OrganizationRole", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("HealthAlerts");

                    b.Navigation("HealthConfig");

                    b.Navigation("HealthStatus");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.SensorType", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
