<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoData.Wildlife.Contracts\EcoData.Wildlife.Contracts.csproj" />
    <ProjectReference Include="..\EcoData.Wildlife.Database\EcoData.Wildlife.Database.csproj" />
  </ItemGroup>

</Project>
